# Generated by Django 3.0.5 on 2020-05-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20200424_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
