# Generated by Django 3.0.5 on 2020-04-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCidade', models.CharField(max_length=15, verbose_name='Cidade')),
                ('nomeUF', models.CharField(max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruaEndereco', models.CharField(max_length=80, verbose_name='Endereço do Cliente')),
                ('nroEndereco', models.IntegerField(verbose_name='Numero do Cliente')),
                ('nomeBairro', models.CharField(max_length=45, verbose_name='Nome do Cliente')),
                ('cidadeEndereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cidade', verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=45, verbose_name='Nome do Cliente')),
                ('numeroCpf', models.CharField(max_length=14, verbose_name='Número do CPF')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('codigoEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Endereco', verbose_name='Endereço')),
            ],
        ),
    ]
