# Generated by Django 3.0.5 on 2020-04-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='ruaEndereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='logradouroEndereco',
            field=models.CharField(default=1, max_length=40, verbose_name='Endereço do Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='nomeBairro',
            field=models.CharField(max_length=45, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='nroEndereco',
            field=models.IntegerField(verbose_name='Número do Cliente'),
        ),
    ]
