# Generated by Django 3.0.5 on 2020-04-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200417_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='nroEndereco',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número do Cliente'),
        ),
    ]
